# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layouts/base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.h_layout_central = QtGui.QHBoxLayout()
        self.h_layout_central.setContentsMargins(0, -1, 0, -1)
        self.h_layout_central.setObjectName(_fromUtf8("h_layout_central"))
        self.v_layou_options = QtGui.QVBoxLayout()
        self.v_layou_options.setObjectName(_fromUtf8("v_layou_options"))
        self.tabs_options = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_options.sizePolicy().hasHeightForWidth())
        self.tabs_options.setSizePolicy(sizePolicy)
        self.tabs_options.setMaximumSize(QtCore.QSize(16777215, 265))
        self.tabs_options.setObjectName(_fromUtf8("tabs_options"))
        self.tab_basics = QtGui.QWidget()
        self.tab_basics.setObjectName(_fromUtf8("tab_basics"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab_basics)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.v_layout_basics = QtGui.QVBoxLayout()
        self.v_layout_basics.setObjectName(_fromUtf8("v_layout_basics"))
        self.h_layout_format = QtGui.QHBoxLayout()
        self.h_layout_format.setContentsMargins(-1, -1, -1, 0)
        self.h_layout_format.setObjectName(_fromUtf8("h_layout_format"))
        self.lbl_format = QtGui.QLabel(self.tab_basics)
        self.lbl_format.setObjectName(_fromUtf8("lbl_format"))
        self.h_layout_format.addWidget(self.lbl_format)
        self.btn_format = QtGui.QPushButton(self.tab_basics)
        self.btn_format.setObjectName(_fromUtf8("btn_format"))
        self.h_layout_format.addWidget(self.btn_format)
        self.v_layout_basics.addLayout(self.h_layout_format)
        self.cb_format = QtGui.QComboBox(self.tab_basics)
        self.cb_format.setObjectName(_fromUtf8("cb_format"))
        self.v_layout_basics.addWidget(self.cb_format)
        self.line_format = QtGui.QFrame(self.tab_basics)
        self.line_format.setFrameShape(QtGui.QFrame.HLine)
        self.line_format.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_format.setObjectName(_fromUtf8("line_format"))
        self.v_layout_basics.addWidget(self.line_format)
        self.h_layout_brightness = QtGui.QHBoxLayout()
        self.h_layout_brightness.setContentsMargins(-1, 0, -1, -1)
        self.h_layout_brightness.setObjectName(_fromUtf8("h_layout_brightness"))
        self.lbl_brightness = QtGui.QLabel(self.tab_basics)
        self.lbl_brightness.setObjectName(_fromUtf8("lbl_brightness"))
        self.h_layout_brightness.addWidget(self.lbl_brightness)
        self.btn_brightness = QtGui.QPushButton(self.tab_basics)
        self.btn_brightness.setObjectName(_fromUtf8("btn_brightness"))
        self.h_layout_brightness.addWidget(self.btn_brightness)
        self.v_layout_basics.addLayout(self.h_layout_brightness)
        self.sl_brightness = QtGui.QSlider(self.tab_basics)
        self.sl_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.sl_brightness.setObjectName(_fromUtf8("sl_brightness"))
        self.v_layout_basics.addWidget(self.sl_brightness)
        self.line_brightness = QtGui.QFrame(self.tab_basics)
        self.line_brightness.setFrameShape(QtGui.QFrame.HLine)
        self.line_brightness.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_brightness.setObjectName(_fromUtf8("line_brightness"))
        self.v_layout_basics.addWidget(self.line_brightness)
        self.h_layout_contrast = QtGui.QHBoxLayout()
        self.h_layout_contrast.setContentsMargins(-1, 0, -1, -1)
        self.h_layout_contrast.setObjectName(_fromUtf8("h_layout_contrast"))
        self.lbl_contrast = QtGui.QLabel(self.tab_basics)
        self.lbl_contrast.setObjectName(_fromUtf8("lbl_contrast"))
        self.h_layout_contrast.addWidget(self.lbl_contrast)
        self.btn_contrast = QtGui.QPushButton(self.tab_basics)
        self.btn_contrast.setObjectName(_fromUtf8("btn_contrast"))
        self.h_layout_contrast.addWidget(self.btn_contrast)
        self.v_layout_basics.addLayout(self.h_layout_contrast)
        self.sl_contrast = QtGui.QSlider(self.tab_basics)
        self.sl_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.sl_contrast.setObjectName(_fromUtf8("sl_contrast"))
        self.v_layout_basics.addWidget(self.sl_contrast)
        self.horizontalLayout_2.addLayout(self.v_layout_basics)
        self.tabs_options.addTab(self.tab_basics, _fromUtf8(""))
        self.tab_noise = QtGui.QWidget()
        self.tab_noise.setObjectName(_fromUtf8("tab_noise"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.tab_noise)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.v_layout_noise = QtGui.QVBoxLayout()
        self.v_layout_noise.setObjectName(_fromUtf8("v_layout_noise"))
        self.lbl_noise = QtGui.QLabel(self.tab_noise)
        self.lbl_noise.setObjectName(_fromUtf8("lbl_noise"))
        self.v_layout_noise.addWidget(self.lbl_noise)
        self.cb_noise = QtGui.QComboBox(self.tab_noise)
        self.cb_noise.setObjectName(_fromUtf8("cb_noise"))
        self.v_layout_noise.addWidget(self.cb_noise)
        self.lbl_noise_amount = QtGui.QLabel(self.tab_noise)
        self.lbl_noise_amount.setObjectName(_fromUtf8("lbl_noise_amount"))
        self.v_layout_noise.addWidget(self.lbl_noise_amount)
        self.sl_noise_amount = QtGui.QSlider(self.tab_noise)
        self.sl_noise_amount.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sl_noise_amount.setOrientation(QtCore.Qt.Horizontal)
        self.sl_noise_amount.setObjectName(_fromUtf8("sl_noise_amount"))
        self.v_layout_noise.addWidget(self.sl_noise_amount)
        self.lbl_noise_params = QtGui.QLabel(self.tab_noise)
        self.lbl_noise_params.setObjectName(_fromUtf8("lbl_noise_params"))
        self.v_layout_noise.addWidget(self.lbl_noise_params)
        self.edit_noise_params = QtGui.QLineEdit(self.tab_noise)
        self.edit_noise_params.setObjectName(_fromUtf8("edit_noise_params"))
        self.v_layout_noise.addWidget(self.edit_noise_params)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.v_layout_noise.addItem(spacerItem)
        self.btn_insert_noise = QtGui.QPushButton(self.tab_noise)
        self.btn_insert_noise.setObjectName(_fromUtf8("btn_insert_noise"))
        self.v_layout_noise.addWidget(self.btn_insert_noise)
        self.horizontalLayout_9.addLayout(self.v_layout_noise)
        self.tabs_options.addTab(self.tab_noise, _fromUtf8(""))
        self.tab_filters = QtGui.QWidget()
        self.tab_filters.setObjectName(_fromUtf8("tab_filters"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_filters)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.v_layout_filter = QtGui.QVBoxLayout()
        self.v_layout_filter.setContentsMargins(0, -1, -1, -1)
        self.v_layout_filter.setObjectName(_fromUtf8("v_layout_filter"))
        self.lbl_filter = QtGui.QLabel(self.tab_filters)
        self.lbl_filter.setObjectName(_fromUtf8("lbl_filter"))
        self.v_layout_filter.addWidget(self.lbl_filter)
        self.cb_filter = QtGui.QComboBox(self.tab_filters)
        self.cb_filter.setObjectName(_fromUtf8("cb_filter"))
        self.v_layout_filter.addWidget(self.cb_filter)
        self.lbl_filter_size = QtGui.QLabel(self.tab_filters)
        self.lbl_filter_size.setObjectName(_fromUtf8("lbl_filter_size"))
        self.v_layout_filter.addWidget(self.lbl_filter_size)
        self.sl_filter_size = QtGui.QSlider(self.tab_filters)
        self.sl_filter_size.setOrientation(QtCore.Qt.Horizontal)
        self.sl_filter_size.setObjectName(_fromUtf8("sl_filter_size"))
        self.v_layout_filter.addWidget(self.sl_filter_size)
        self.lbl_filter_params = QtGui.QLabel(self.tab_filters)
        self.lbl_filter_params.setObjectName(_fromUtf8("lbl_filter_params"))
        self.v_layout_filter.addWidget(self.lbl_filter_params)
        self.edit_filter_params = QtGui.QLineEdit(self.tab_filters)
        self.edit_filter_params.setObjectName(_fromUtf8("edit_filter_params"))
        self.v_layout_filter.addWidget(self.edit_filter_params)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.v_layout_filter.addItem(spacerItem1)
        self.btn_insert_filter = QtGui.QPushButton(self.tab_filters)
        self.btn_insert_filter.setObjectName(_fromUtf8("btn_insert_filter"))
        self.v_layout_filter.addWidget(self.btn_insert_filter)
        self.horizontalLayout_3.addLayout(self.v_layout_filter)
        self.tabs_options.addTab(self.tab_filters, _fromUtf8(""))
        self.tab_morph = QtGui.QWidget()
        self.tab_morph.setObjectName(_fromUtf8("tab_morph"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_morph)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.v_layout_morph = QtGui.QVBoxLayout()
        self.v_layout_morph.setObjectName(_fromUtf8("v_layout_morph"))
        self.label_morph_type = QtGui.QLabel(self.tab_morph)
        self.label_morph_type.setObjectName(_fromUtf8("label_morph_type"))
        self.v_layout_morph.addWidget(self.label_morph_type)
        self.cb_morph_type = QtGui.QComboBox(self.tab_morph)
        self.cb_morph_type.setObjectName(_fromUtf8("cb_morph_type"))
        self.v_layout_morph.addWidget(self.cb_morph_type)
        self.radio_morph_binary = QtGui.QRadioButton(self.tab_morph)
        self.radio_morph_binary.setChecked(True)
        self.radio_morph_binary.setObjectName(_fromUtf8("radio_morph_binary"))
        self.v_layout_morph.addWidget(self.radio_morph_binary)
        self.radio_morph_grey = QtGui.QRadioButton(self.tab_morph)
        self.radio_morph_grey.setObjectName(_fromUtf8("radio_morph_grey"))
        self.v_layout_morph.addWidget(self.radio_morph_grey)
        self.lbl_morph_size = QtGui.QLabel(self.tab_morph)
        self.lbl_morph_size.setObjectName(_fromUtf8("lbl_morph_size"))
        self.v_layout_morph.addWidget(self.lbl_morph_size)
        self.sl_morph_size = QtGui.QSlider(self.tab_morph)
        self.sl_morph_size.setOrientation(QtCore.Qt.Horizontal)
        self.sl_morph_size.setObjectName(_fromUtf8("sl_morph_size"))
        self.v_layout_morph.addWidget(self.sl_morph_size)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.v_layout_morph.addItem(spacerItem2)
        self.btn_morph = QtGui.QPushButton(self.tab_morph)
        self.btn_morph.setObjectName(_fromUtf8("btn_morph"))
        self.v_layout_morph.addWidget(self.btn_morph)
        self.horizontalLayout_4.addLayout(self.v_layout_morph)
        self.tabs_options.addTab(self.tab_morph, _fromUtf8(""))
        self.tab_segmentation = QtGui.QWidget()
        self.tab_segmentation.setObjectName(_fromUtf8("tab_segmentation"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_segmentation)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.v_layout_segmentation = QtGui.QVBoxLayout()
        self.v_layout_segmentation.setObjectName(_fromUtf8("v_layout_segmentation"))
        self.lbl_hist_segmentation = QtGui.QLabel(self.tab_segmentation)
        self.lbl_hist_segmentation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hist_segmentation.setObjectName(_fromUtf8("lbl_hist_segmentation"))
        self.v_layout_segmentation.addWidget(self.lbl_hist_segmentation)
        self.line_hist_seg = QtGui.QFrame(self.tab_segmentation)
        self.line_hist_seg.setFrameShape(QtGui.QFrame.HLine)
        self.line_hist_seg.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_hist_seg.setObjectName(_fromUtf8("line_hist_seg"))
        self.v_layout_segmentation.addWidget(self.line_hist_seg)
        self.lbl_seg_threshold = QtGui.QLabel(self.tab_segmentation)
        self.lbl_seg_threshold.setObjectName(_fromUtf8("lbl_seg_threshold"))
        self.v_layout_segmentation.addWidget(self.lbl_seg_threshold)
        self.sl_segmentation_th = QtGui.QSlider(self.tab_segmentation)
        self.sl_segmentation_th.setOrientation(QtCore.Qt.Horizontal)
        self.sl_segmentation_th.setObjectName(_fromUtf8("sl_segmentation_th"))
        self.v_layout_segmentation.addWidget(self.sl_segmentation_th)
        self.line_seg_threshold = QtGui.QFrame(self.tab_segmentation)
        self.line_seg_threshold.setFrameShape(QtGui.QFrame.HLine)
        self.line_seg_threshold.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_seg_threshold.setObjectName(_fromUtf8("line_seg_threshold"))
        self.v_layout_segmentation.addWidget(self.line_seg_threshold)
        self.radio_seg_mean_th = QtGui.QRadioButton(self.tab_segmentation)
        self.radio_seg_mean_th.setObjectName(_fromUtf8("radio_seg_mean_th"))
        self.v_layout_segmentation.addWidget(self.radio_seg_mean_th)
        self.radio_seg_median_th = QtGui.QRadioButton(self.tab_segmentation)
        self.radio_seg_median_th.setChecked(True)
        self.radio_seg_median_th.setObjectName(_fromUtf8("radio_seg_median_th"))
        self.v_layout_segmentation.addWidget(self.radio_seg_median_th)
        self.line_seg_type = QtGui.QFrame(self.tab_segmentation)
        self.line_seg_type.setFrameShape(QtGui.QFrame.HLine)
        self.line_seg_type.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_seg_type.setObjectName(_fromUtf8("line_seg_type"))
        self.v_layout_segmentation.addWidget(self.line_seg_type)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.v_layout_segmentation.addItem(spacerItem3)
        self.btn_hist_segmentation = QtGui.QPushButton(self.tab_segmentation)
        self.btn_hist_segmentation.setObjectName(_fromUtf8("btn_hist_segmentation"))
        self.v_layout_segmentation.addWidget(self.btn_hist_segmentation)
        self.horizontalLayout_5.addLayout(self.v_layout_segmentation)
        self.tabs_options.addTab(self.tab_segmentation, _fromUtf8(""))
        self.tab_misc = QtGui.QWidget()
        self.tab_misc.setObjectName(_fromUtf8("tab_misc"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.tab_misc)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.v_layout_misc = QtGui.QVBoxLayout()
        self.v_layout_misc.setObjectName(_fromUtf8("v_layout_misc"))
        self.btn_labels = QtGui.QPushButton(self.tab_misc)
        self.btn_labels.setObjectName(_fromUtf8("btn_labels"))
        self.v_layout_misc.addWidget(self.btn_labels)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.v_layout_misc.addItem(spacerItem4)
        self.horizontalLayout_10.addLayout(self.v_layout_misc)
        self.tabs_options.addTab(self.tab_misc, _fromUtf8(""))
        self.v_layou_options.addWidget(self.tabs_options)
        self.h_layout_options = QtGui.QHBoxLayout()
        self.h_layout_options.setObjectName(_fromUtf8("h_layout_options"))
        self.btn_equalize = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_equalize.sizePolicy().hasHeightForWidth())
        self.btn_equalize.setSizePolicy(sizePolicy)
        self.btn_equalize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_equalize.setFlat(False)
        self.btn_equalize.setObjectName(_fromUtf8("btn_equalize"))
        self.h_layout_options.addWidget(self.btn_equalize)
        self.radio_compare = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_compare.sizePolicy().hasHeightForWidth())
        self.radio_compare.setSizePolicy(sizePolicy)
        self.radio_compare.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radio_compare.setAutoExclusive(False)
        self.radio_compare.setObjectName(_fromUtf8("radio_compare"))
        self.h_layout_options.addWidget(self.radio_compare)
        self.radio_hist = QtGui.QRadioButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_hist.sizePolicy().hasHeightForWidth())
        self.radio_hist.setSizePolicy(sizePolicy)
        self.radio_hist.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radio_hist.setChecked(True)
        self.radio_hist.setAutoExclusive(False)
        self.radio_hist.setObjectName(_fromUtf8("radio_hist"))
        self.h_layout_options.addWidget(self.radio_hist)
        self.v_layou_options.addLayout(self.h_layout_options)
        self.h_layout_original_image = QtGui.QHBoxLayout()
        self.h_layout_original_image.setObjectName(_fromUtf8("h_layout_original_image"))
        self.replace_original_image = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_original_image.sizePolicy().hasHeightForWidth())
        self.replace_original_image.setSizePolicy(sizePolicy)
        self.replace_original_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.replace_original_image.setObjectName(_fromUtf8("replace_original_image"))
        self.h_layout_original_image.addWidget(self.replace_original_image)
        self.v_layou_options.addLayout(self.h_layout_original_image)
        self.h_layout_central.addLayout(self.v_layou_options)
        self.v_layout_edited_image = QtGui.QVBoxLayout()
        self.v_layout_edited_image.setContentsMargins(0, -1, -1, -1)
        self.v_layout_edited_image.setObjectName(_fromUtf8("v_layout_edited_image"))
        self.replace_edited_image = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_edited_image.sizePolicy().hasHeightForWidth())
        self.replace_edited_image.setSizePolicy(sizePolicy)
        self.replace_edited_image.setObjectName(_fromUtf8("replace_edited_image"))
        self.v_layout_edited_image.addWidget(self.replace_edited_image)
        self.h_layout_central.addLayout(self.v_layout_edited_image)
        self.verticalLayout.addLayout(self.h_layout_central)
        self.h_layout_status = QtGui.QHBoxLayout()
        self.h_layout_status.setContentsMargins(-1, 0, -1, -1)
        self.h_layout_status.setObjectName(_fromUtf8("h_layout_status"))
        self.lbl_fixed_status = QtGui.QLabel(self.centralwidget)
        self.lbl_fixed_status.setObjectName(_fromUtf8("lbl_fixed_status"))
        self.h_layout_status.addWidget(self.lbl_fixed_status)
        self.lbl_status_msg = QtGui.QLabel(self.centralwidget)
        self.lbl_status_msg.setObjectName(_fromUtf8("lbl_status_msg"))
        self.h_layout_status.addWidget(self.lbl_status_msg)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.h_layout_status.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.h_layout_status)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArquivo = QtGui.QMenu(self.menubar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuSobre = QtGui.QMenu(self.menubar)
        self.menuSobre.setObjectName(_fromUtf8("menuSobre"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuFerramentas = QtGui.QMenu(self.menubar)
        self.menuFerramentas.setObjectName(_fromUtf8("menuFerramentas"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtGui.QAction(MainWindow)
        self.actionAbrir.setObjectName(_fromUtf8("actionAbrir"))
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setObjectName(_fromUtf8("actionReset"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionVer_Historico = QtGui.QAction(MainWindow)
        self.actionVer_Historico.setObjectName(_fromUtf8("actionVer_Historico"))
        self.actionSalvar_em_docx = QtGui.QAction(MainWindow)
        self.actionSalvar_em_docx.setObjectName(_fromUtf8("actionSalvar_em_docx"))
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionReset)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionVer_Historico)
        self.menuFerramentas.addAction(self.actionSalvar_em_docx)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFerramentas.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Medical Images App", None))
        self.lbl_format.setText(_translate("MainWindow", "Formato:", None))
        self.btn_format.setText(_translate("MainWindow", "Apply", None))
        self.lbl_brightness.setText(_translate("MainWindow", "Brilho:", None))
        self.btn_brightness.setText(_translate("MainWindow", "Apply", None))
        self.lbl_contrast.setText(_translate("MainWindow", "Contraste:", None))
        self.btn_contrast.setText(_translate("MainWindow", "Apply", None))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_basics), _translate("MainWindow", "Basics", None))
        self.lbl_noise.setText(_translate("MainWindow", "Ruído:", None))
        self.lbl_noise_amount.setText(_translate("MainWindow", "Quantidade:", None))
        self.lbl_noise_params.setText(_translate("MainWindow", "Parâmetros:", None))
        self.btn_insert_noise.setText(_translate("MainWindow", "Inserir", None))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_noise), _translate("MainWindow", "Ruido", None))
        self.lbl_filter.setText(_translate("MainWindow", "Filtro:", None))
        self.lbl_filter_size.setText(_translate("MainWindow", "Size:", None))
        self.lbl_filter_params.setText(_translate("MainWindow", "Parâmetros:", None))
        self.btn_insert_filter.setText(_translate("MainWindow", "Inserir", None))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_filters), _translate("MainWindow", "Filtros", None))
        self.label_morph_type.setText(_translate("MainWindow", "Morph:", None))
        self.radio_morph_binary.setText(_translate("MainWindow", "Binary", None))
        self.radio_morph_grey.setText(_translate("MainWindow", "Grey", None))
        self.lbl_morph_size.setText(_translate("MainWindow", "Size(px):", None))
        self.btn_morph.setText(_translate("MainWindow", "Apply", None))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_morph), _translate("MainWindow", "Morph", None))
        self.lbl_hist_segmentation.setText(_translate("MainWindow", "Histogram-Based", None))
        self.lbl_seg_threshold.setText(_translate("MainWindow", "Limiar:", None))
        self.radio_seg_mean_th.setText(_translate("MainWindow", "Media", None))
        self.radio_seg_median_th.setText(_translate("MainWindow", "Mediana", None))
        self.btn_hist_segmentation.setText(_translate("MainWindow", "Apply", None))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_segmentation), _translate("MainWindow", "Segmentação", None))
        self.btn_labels.setText(_translate("MainWindow", "Labels", None))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_misc), _translate("MainWindow", "Misc", None))
        self.btn_equalize.setText(_translate("MainWindow", "Equalizar", None))
        self.radio_compare.setText(_translate("MainWindow", "Comparar", None))
        self.radio_hist.setText(_translate("MainWindow", "Histograma", None))
        self.replace_original_image.setText(_translate("MainWindow", "Original Image", None))
        self.replace_edited_image.setText(_translate("MainWindow", "Edited Image", None))
        self.lbl_fixed_status.setText(_translate("MainWindow", "Status:", None))
        self.lbl_status_msg.setText(_translate("MainWindow", "Iniciado.", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo", None))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Editar", None))
        self.menuFerramentas.setTitle(_translate("MainWindow", "Ferramentas", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Opções", None))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir", None))
        self.actionReset.setText(_translate("MainWindow", "Reset", None))
        self.actionSobre.setText(_translate("MainWindow", "Sobre", None))
        self.actionUndo.setText(_translate("MainWindow", "Desfazer", None))
        self.actionVer_Historico.setText(_translate("MainWindow", "Ver Historico", None))
        self.actionSalvar_em_docx.setText(_translate("MainWindow", "Salvar em .docx", None))

