# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layouts/base.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.h_layout_central = QtWidgets.QHBoxLayout()
        self.h_layout_central.setContentsMargins(0, -1, 0, -1)
        self.h_layout_central.setObjectName("h_layout_central")
        self.v_layou_options = QtWidgets.QVBoxLayout()
        self.v_layou_options.setObjectName("v_layou_options")
        self.tabs_options = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_options.sizePolicy().hasHeightForWidth())
        self.tabs_options.setSizePolicy(sizePolicy)
        self.tabs_options.setMaximumSize(QtCore.QSize(16777215, 265))
        self.tabs_options.setObjectName("tabs_options")
        self.tab_basics = QtWidgets.QWidget()
        self.tab_basics.setObjectName("tab_basics")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_basics)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.v_layout_basics = QtWidgets.QVBoxLayout()
        self.v_layout_basics.setObjectName("v_layout_basics")
        self.h_layout_format = QtWidgets.QHBoxLayout()
        self.h_layout_format.setContentsMargins(-1, -1, -1, 0)
        self.h_layout_format.setObjectName("h_layout_format")
        self.lbl_format = QtWidgets.QLabel(self.tab_basics)
        self.lbl_format.setObjectName("lbl_format")
        self.h_layout_format.addWidget(self.lbl_format)
        self.btn_format = QtWidgets.QPushButton(self.tab_basics)
        self.btn_format.setObjectName("btn_format")
        self.h_layout_format.addWidget(self.btn_format)
        self.v_layout_basics.addLayout(self.h_layout_format)
        self.cb_format = QtWidgets.QComboBox(self.tab_basics)
        self.cb_format.setObjectName("cb_format")
        self.v_layout_basics.addWidget(self.cb_format)
        self.line_format = QtWidgets.QFrame(self.tab_basics)
        self.line_format.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_format.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_format.setObjectName("line_format")
        self.v_layout_basics.addWidget(self.line_format)
        self.h_layout_brightness = QtWidgets.QHBoxLayout()
        self.h_layout_brightness.setContentsMargins(-1, 0, -1, -1)
        self.h_layout_brightness.setObjectName("h_layout_brightness")
        self.lbl_brightness = QtWidgets.QLabel(self.tab_basics)
        self.lbl_brightness.setObjectName("lbl_brightness")
        self.h_layout_brightness.addWidget(self.lbl_brightness)
        self.btn_brightness = QtWidgets.QPushButton(self.tab_basics)
        self.btn_brightness.setObjectName("btn_brightness")
        self.h_layout_brightness.addWidget(self.btn_brightness)
        self.v_layout_basics.addLayout(self.h_layout_brightness)
        self.sl_brightness = QtWidgets.QSlider(self.tab_basics)
        self.sl_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.sl_brightness.setObjectName("sl_brightness")
        self.v_layout_basics.addWidget(self.sl_brightness)
        self.line_brightness = QtWidgets.QFrame(self.tab_basics)
        self.line_brightness.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_brightness.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_brightness.setObjectName("line_brightness")
        self.v_layout_basics.addWidget(self.line_brightness)
        self.h_layout_contrast = QtWidgets.QHBoxLayout()
        self.h_layout_contrast.setContentsMargins(-1, 0, -1, -1)
        self.h_layout_contrast.setObjectName("h_layout_contrast")
        self.lbl_contrast = QtWidgets.QLabel(self.tab_basics)
        self.lbl_contrast.setObjectName("lbl_contrast")
        self.h_layout_contrast.addWidget(self.lbl_contrast)
        self.btn_contrast = QtWidgets.QPushButton(self.tab_basics)
        self.btn_contrast.setObjectName("btn_contrast")
        self.h_layout_contrast.addWidget(self.btn_contrast)
        self.v_layout_basics.addLayout(self.h_layout_contrast)
        self.sl_contrast = QtWidgets.QSlider(self.tab_basics)
        self.sl_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.sl_contrast.setObjectName("sl_contrast")
        self.v_layout_basics.addWidget(self.sl_contrast)
        self.horizontalLayout_2.addLayout(self.v_layout_basics)
        self.tabs_options.addTab(self.tab_basics, "")
        self.tab_noise = QtWidgets.QWidget()
        self.tab_noise.setObjectName("tab_noise")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab_noise)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.v_layout_noise = QtWidgets.QVBoxLayout()
        self.v_layout_noise.setObjectName("v_layout_noise")
        self.lbl_noise = QtWidgets.QLabel(self.tab_noise)
        self.lbl_noise.setObjectName("lbl_noise")
        self.v_layout_noise.addWidget(self.lbl_noise)
        self.cb_noise = QtWidgets.QComboBox(self.tab_noise)
        self.cb_noise.setObjectName("cb_noise")
        self.v_layout_noise.addWidget(self.cb_noise)
        self.lbl_noise_amount = QtWidgets.QLabel(self.tab_noise)
        self.lbl_noise_amount.setObjectName("lbl_noise_amount")
        self.v_layout_noise.addWidget(self.lbl_noise_amount)
        self.sl_noise_amount = QtWidgets.QSlider(self.tab_noise)
        self.sl_noise_amount.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sl_noise_amount.setOrientation(QtCore.Qt.Horizontal)
        self.sl_noise_amount.setObjectName("sl_noise_amount")
        self.v_layout_noise.addWidget(self.sl_noise_amount)
        self.lbl_noise_params = QtWidgets.QLabel(self.tab_noise)
        self.lbl_noise_params.setObjectName("lbl_noise_params")
        self.v_layout_noise.addWidget(self.lbl_noise_params)
        self.edit_noise_params = QtWidgets.QLineEdit(self.tab_noise)
        self.edit_noise_params.setObjectName("edit_noise_params")
        self.v_layout_noise.addWidget(self.edit_noise_params)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_layout_noise.addItem(spacerItem)
        self.btn_insert_noise = QtWidgets.QPushButton(self.tab_noise)
        self.btn_insert_noise.setObjectName("btn_insert_noise")
        self.v_layout_noise.addWidget(self.btn_insert_noise)
        self.horizontalLayout_9.addLayout(self.v_layout_noise)
        self.tabs_options.addTab(self.tab_noise, "")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_filters)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.v_layout_filter = QtWidgets.QVBoxLayout()
        self.v_layout_filter.setContentsMargins(0, -1, -1, -1)
        self.v_layout_filter.setObjectName("v_layout_filter")
        self.lbl_filter = QtWidgets.QLabel(self.tab_filters)
        self.lbl_filter.setObjectName("lbl_filter")
        self.v_layout_filter.addWidget(self.lbl_filter)
        self.cb_filter = QtWidgets.QComboBox(self.tab_filters)
        self.cb_filter.setObjectName("cb_filter")
        self.v_layout_filter.addWidget(self.cb_filter)
        self.lbl_filter_size = QtWidgets.QLabel(self.tab_filters)
        self.lbl_filter_size.setObjectName("lbl_filter_size")
        self.v_layout_filter.addWidget(self.lbl_filter_size)
        self.sl_filter_size = QtWidgets.QSlider(self.tab_filters)
        self.sl_filter_size.setOrientation(QtCore.Qt.Horizontal)
        self.sl_filter_size.setObjectName("sl_filter_size")
        self.v_layout_filter.addWidget(self.sl_filter_size)
        self.lbl_filter_params = QtWidgets.QLabel(self.tab_filters)
        self.lbl_filter_params.setObjectName("lbl_filter_params")
        self.v_layout_filter.addWidget(self.lbl_filter_params)
        self.edit_filter_params = QtWidgets.QLineEdit(self.tab_filters)
        self.edit_filter_params.setObjectName("edit_filter_params")
        self.v_layout_filter.addWidget(self.edit_filter_params)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_layout_filter.addItem(spacerItem1)
        self.btn_insert_filter = QtWidgets.QPushButton(self.tab_filters)
        self.btn_insert_filter.setObjectName("btn_insert_filter")
        self.v_layout_filter.addWidget(self.btn_insert_filter)
        self.horizontalLayout_3.addLayout(self.v_layout_filter)
        self.tabs_options.addTab(self.tab_filters, "")
        self.tab_morph = QtWidgets.QWidget()
        self.tab_morph.setObjectName("tab_morph")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_morph)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.v_layout_morph = QtWidgets.QVBoxLayout()
        self.v_layout_morph.setObjectName("v_layout_morph")
        self.label_morph_type = QtWidgets.QLabel(self.tab_morph)
        self.label_morph_type.setObjectName("label_morph_type")
        self.v_layout_morph.addWidget(self.label_morph_type)
        self.cb_morph_type = QtWidgets.QComboBox(self.tab_morph)
        self.cb_morph_type.setObjectName("cb_morph_type")
        self.v_layout_morph.addWidget(self.cb_morph_type)
        self.radio_morph_binary = QtWidgets.QRadioButton(self.tab_morph)
        self.radio_morph_binary.setChecked(True)
        self.radio_morph_binary.setObjectName("radio_morph_binary")
        self.v_layout_morph.addWidget(self.radio_morph_binary)
        self.radio_morph_grey = QtWidgets.QRadioButton(self.tab_morph)
        self.radio_morph_grey.setObjectName("radio_morph_grey")
        self.v_layout_morph.addWidget(self.radio_morph_grey)
        self.lbl_morph_size = QtWidgets.QLabel(self.tab_morph)
        self.lbl_morph_size.setObjectName("lbl_morph_size")
        self.v_layout_morph.addWidget(self.lbl_morph_size)
        self.sl_morph_size = QtWidgets.QSlider(self.tab_morph)
        self.sl_morph_size.setOrientation(QtCore.Qt.Horizontal)
        self.sl_morph_size.setObjectName("sl_morph_size")
        self.v_layout_morph.addWidget(self.sl_morph_size)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_layout_morph.addItem(spacerItem2)
        self.btn_morph = QtWidgets.QPushButton(self.tab_morph)
        self.btn_morph.setObjectName("btn_morph")
        self.v_layout_morph.addWidget(self.btn_morph)
        self.horizontalLayout_4.addLayout(self.v_layout_morph)
        self.tabs_options.addTab(self.tab_morph, "")
        self.tab_segmentation = QtWidgets.QWidget()
        self.tab_segmentation.setObjectName("tab_segmentation")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_segmentation)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.v_layout_segmentation = QtWidgets.QVBoxLayout()
        self.v_layout_segmentation.setObjectName("v_layout_segmentation")
        self.lbl_hist_segmentation = QtWidgets.QLabel(self.tab_segmentation)
        self.lbl_hist_segmentation.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hist_segmentation.setObjectName("lbl_hist_segmentation")
        self.v_layout_segmentation.addWidget(self.lbl_hist_segmentation)
        self.line_hist_seg = QtWidgets.QFrame(self.tab_segmentation)
        self.line_hist_seg.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_hist_seg.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_hist_seg.setObjectName("line_hist_seg")
        self.v_layout_segmentation.addWidget(self.line_hist_seg)
        self.lbl_seg_threshold = QtWidgets.QLabel(self.tab_segmentation)
        self.lbl_seg_threshold.setObjectName("lbl_seg_threshold")
        self.v_layout_segmentation.addWidget(self.lbl_seg_threshold)
        self.sl_segmentation_th = QtWidgets.QSlider(self.tab_segmentation)
        self.sl_segmentation_th.setOrientation(QtCore.Qt.Horizontal)
        self.sl_segmentation_th.setObjectName("sl_segmentation_th")
        self.v_layout_segmentation.addWidget(self.sl_segmentation_th)
        self.line_seg_threshold = QtWidgets.QFrame(self.tab_segmentation)
        self.line_seg_threshold.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_seg_threshold.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_seg_threshold.setObjectName("line_seg_threshold")
        self.v_layout_segmentation.addWidget(self.line_seg_threshold)
        self.radio_seg_mean_th = QtWidgets.QRadioButton(self.tab_segmentation)
        self.radio_seg_mean_th.setObjectName("radio_seg_mean_th")
        self.v_layout_segmentation.addWidget(self.radio_seg_mean_th)
        self.radio_seg_median_th = QtWidgets.QRadioButton(self.tab_segmentation)
        self.radio_seg_median_th.setChecked(True)
        self.radio_seg_median_th.setObjectName("radio_seg_median_th")
        self.v_layout_segmentation.addWidget(self.radio_seg_median_th)
        self.line_seg_type = QtWidgets.QFrame(self.tab_segmentation)
        self.line_seg_type.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_seg_type.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_seg_type.setObjectName("line_seg_type")
        self.v_layout_segmentation.addWidget(self.line_seg_type)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_layout_segmentation.addItem(spacerItem3)
        self.btn_hist_segmentation = QtWidgets.QPushButton(self.tab_segmentation)
        self.btn_hist_segmentation.setObjectName("btn_hist_segmentation")
        self.v_layout_segmentation.addWidget(self.btn_hist_segmentation)
        self.horizontalLayout_5.addLayout(self.v_layout_segmentation)
        self.tabs_options.addTab(self.tab_segmentation, "")
        self.tab_misc = QtWidgets.QWidget()
        self.tab_misc.setObjectName("tab_misc")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.tab_misc)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.v_layout_misc = QtWidgets.QVBoxLayout()
        self.v_layout_misc.setObjectName("v_layout_misc")
        self.btn_labels = QtWidgets.QPushButton(self.tab_misc)
        self.btn_labels.setObjectName("btn_labels")
        self.v_layout_misc.addWidget(self.btn_labels)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.v_layout_misc.addItem(spacerItem4)
        self.horizontalLayout_10.addLayout(self.v_layout_misc)
        self.tabs_options.addTab(self.tab_misc, "")
        self.v_layou_options.addWidget(self.tabs_options)
        self.h_layout_options = QtWidgets.QHBoxLayout()
        self.h_layout_options.setObjectName("h_layout_options")
        self.btn_equalize = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_equalize.sizePolicy().hasHeightForWidth())
        self.btn_equalize.setSizePolicy(sizePolicy)
        self.btn_equalize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_equalize.setFlat(False)
        self.btn_equalize.setObjectName("btn_equalize")
        self.h_layout_options.addWidget(self.btn_equalize)
        self.radio_compare = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_compare.sizePolicy().hasHeightForWidth())
        self.radio_compare.setSizePolicy(sizePolicy)
        self.radio_compare.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radio_compare.setAutoExclusive(False)
        self.radio_compare.setObjectName("radio_compare")
        self.h_layout_options.addWidget(self.radio_compare)
        self.radio_hist = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_hist.sizePolicy().hasHeightForWidth())
        self.radio_hist.setSizePolicy(sizePolicy)
        self.radio_hist.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radio_hist.setChecked(True)
        self.radio_hist.setAutoExclusive(False)
        self.radio_hist.setObjectName("radio_hist")
        self.h_layout_options.addWidget(self.radio_hist)
        self.v_layou_options.addLayout(self.h_layout_options)
        self.h_layout_original_image = QtWidgets.QHBoxLayout()
        self.h_layout_original_image.setObjectName("h_layout_original_image")
        self.replace_original_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_original_image.sizePolicy().hasHeightForWidth())
        self.replace_original_image.setSizePolicy(sizePolicy)
        self.replace_original_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.replace_original_image.setObjectName("replace_original_image")
        self.h_layout_original_image.addWidget(self.replace_original_image)
        self.v_layou_options.addLayout(self.h_layout_original_image)
        self.h_layout_central.addLayout(self.v_layou_options)
        self.v_layout_edited_image = QtWidgets.QVBoxLayout()
        self.v_layout_edited_image.setContentsMargins(0, -1, -1, -1)
        self.v_layout_edited_image.setObjectName("v_layout_edited_image")
        self.replace_edited_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_edited_image.sizePolicy().hasHeightForWidth())
        self.replace_edited_image.setSizePolicy(sizePolicy)
        self.replace_edited_image.setObjectName("replace_edited_image")
        self.v_layout_edited_image.addWidget(self.replace_edited_image)
        self.h_layout_central.addLayout(self.v_layout_edited_image)
        self.verticalLayout.addLayout(self.h_layout_central)
        self.h_layout_status = QtWidgets.QHBoxLayout()
        self.h_layout_status.setContentsMargins(-1, 0, -1, -1)
        self.h_layout_status.setObjectName("h_layout_status")
        self.lbl_fixed_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_fixed_status.setObjectName("lbl_fixed_status")
        self.h_layout_status.addWidget(self.lbl_fixed_status)
        self.lbl_status_msg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status_msg.setObjectName("lbl_status_msg")
        self.h_layout_status.addWidget(self.lbl_status_msg)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_layout_status.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.h_layout_status)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFerramentas = QtWidgets.QMenu(self.menubar)
        self.menuFerramentas.setObjectName("menuFerramentas")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionVer_Historico = QtWidgets.QAction(MainWindow)
        self.actionVer_Historico.setObjectName("actionVer_Historico")
        self.actionSalvar_em_docx = QtWidgets.QAction(MainWindow)
        self.actionSalvar_em_docx.setObjectName("actionSalvar_em_docx")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionReset)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionVer_Historico)
        self.menuFerramentas.addAction(self.actionSalvar_em_docx)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFerramentas.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Medical Images App"))
        self.lbl_format.setText(_translate("MainWindow", "Formato:"))
        self.btn_format.setText(_translate("MainWindow", "Apply"))
        self.lbl_brightness.setText(_translate("MainWindow", "Brilho:"))
        self.btn_brightness.setText(_translate("MainWindow", "Apply"))
        self.lbl_contrast.setText(_translate("MainWindow", "Contraste:"))
        self.btn_contrast.setText(_translate("MainWindow", "Apply"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_basics), _translate("MainWindow", "Basics"))
        self.lbl_noise.setText(_translate("MainWindow", "Ruído:"))
        self.lbl_noise_amount.setText(_translate("MainWindow", "Quantidade:"))
        self.lbl_noise_params.setText(_translate("MainWindow", "Parâmetros:"))
        self.btn_insert_noise.setText(_translate("MainWindow", "Inserir"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_noise), _translate("MainWindow", "Ruido"))
        self.lbl_filter.setText(_translate("MainWindow", "Filtro:"))
        self.lbl_filter_size.setText(_translate("MainWindow", "Size:"))
        self.lbl_filter_params.setText(_translate("MainWindow", "Parâmetros:"))
        self.btn_insert_filter.setText(_translate("MainWindow", "Inserir"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_filters), _translate("MainWindow", "Filtros"))
        self.label_morph_type.setText(_translate("MainWindow", "Morph:"))
        self.radio_morph_binary.setText(_translate("MainWindow", "Binary"))
        self.radio_morph_grey.setText(_translate("MainWindow", "Grey"))
        self.lbl_morph_size.setText(_translate("MainWindow", "Size(px):"))
        self.btn_morph.setText(_translate("MainWindow", "Apply"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_morph), _translate("MainWindow", "Morph"))
        self.lbl_hist_segmentation.setText(_translate("MainWindow", "Histogram-Based"))
        self.lbl_seg_threshold.setText(_translate("MainWindow", "Limiar:"))
        self.radio_seg_mean_th.setText(_translate("MainWindow", "Media"))
        self.radio_seg_median_th.setText(_translate("MainWindow", "Mediana"))
        self.btn_hist_segmentation.setText(_translate("MainWindow", "Apply"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_segmentation), _translate("MainWindow", "Segmentação"))
        self.btn_labels.setText(_translate("MainWindow", "Labels"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_misc), _translate("MainWindow", "Misc"))
        self.btn_equalize.setText(_translate("MainWindow", "Equalizar"))
        self.radio_compare.setText(_translate("MainWindow", "Comparar"))
        self.radio_hist.setText(_translate("MainWindow", "Histograma"))
        self.replace_original_image.setText(_translate("MainWindow", "Original Image"))
        self.replace_edited_image.setText(_translate("MainWindow", "Edited Image"))
        self.lbl_fixed_status.setText(_translate("MainWindow", "Status:"))
        self.lbl_status_msg.setText(_translate("MainWindow", "Iniciado."))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre"))
        self.menuEdit.setTitle(_translate("MainWindow", "Editar"))
        self.menuFerramentas.setTitle(_translate("MainWindow", "Ferramentas"))
        self.menuOptions.setTitle(_translate("MainWindow", "Opções"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))
        self.actionUndo.setText(_translate("MainWindow", "Desfazer"))
        self.actionVer_Historico.setText(_translate("MainWindow", "Ver Historico"))
        self.actionSalvar_em_docx.setText(_translate("MainWindow", "Salvar em .docx"))

