# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layouts/base.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.h_layout_central = QtWidgets.QHBoxLayout()
        self.h_layout_central.setContentsMargins(0, -1, 0, -1)
        self.h_layout_central.setObjectName("h_layout_central")
        self.v_layou_options = QtWidgets.QVBoxLayout()
        self.v_layou_options.setObjectName("v_layou_options")
        self.tabs_options = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs_options.sizePolicy().hasHeightForWidth())
        self.tabs_options.setSizePolicy(sizePolicy)
        self.tabs_options.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabs_options.setObjectName("tabs_options")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_filters)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.v_layout_noise = QtWidgets.QVBoxLayout()
        self.v_layout_noise.setObjectName("v_layout_noise")
        self.lbl_noise = QtWidgets.QLabel(self.tab_filters)
        self.lbl_noise.setObjectName("lbl_noise")
        self.v_layout_noise.addWidget(self.lbl_noise)
        self.cb_noise = QtWidgets.QComboBox(self.tab_filters)
        self.cb_noise.setObjectName("cb_noise")
        self.v_layout_noise.addWidget(self.cb_noise)
        self.lbl_noise_amount = QtWidgets.QLabel(self.tab_filters)
        self.lbl_noise_amount.setObjectName("lbl_noise_amount")
        self.v_layout_noise.addWidget(self.lbl_noise_amount)
        self.sl_noise_amount = QtWidgets.QSlider(self.tab_filters)
        self.sl_noise_amount.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sl_noise_amount.setOrientation(QtCore.Qt.Horizontal)
        self.sl_noise_amount.setObjectName("sl_noise_amount")
        self.v_layout_noise.addWidget(self.sl_noise_amount)
        self.lbl_noise_params = QtWidgets.QLabel(self.tab_filters)
        self.lbl_noise_params.setObjectName("lbl_noise_params")
        self.v_layout_noise.addWidget(self.lbl_noise_params)
        self.edit_noise_params = QtWidgets.QLineEdit(self.tab_filters)
        self.edit_noise_params.setObjectName("edit_noise_params")
        self.v_layout_noise.addWidget(self.edit_noise_params)
        self.btn_insert_noise = QtWidgets.QPushButton(self.tab_filters)
        self.btn_insert_noise.setObjectName("btn_insert_noise")
        self.v_layout_noise.addWidget(self.btn_insert_noise)
        self.horizontalLayout_3.addLayout(self.v_layout_noise)
        self.v_layout_filter = QtWidgets.QVBoxLayout()
        self.v_layout_filter.setContentsMargins(0, -1, -1, -1)
        self.v_layout_filter.setObjectName("v_layout_filter")
        self.lbl_filter = QtWidgets.QLabel(self.tab_filters)
        self.lbl_filter.setObjectName("lbl_filter")
        self.v_layout_filter.addWidget(self.lbl_filter)
        self.cb_filter = QtWidgets.QComboBox(self.tab_filters)
        self.cb_filter.setObjectName("cb_filter")
        self.v_layout_filter.addWidget(self.cb_filter)
        self.lbl_filter_size = QtWidgets.QLabel(self.tab_filters)
        self.lbl_filter_size.setObjectName("lbl_filter_size")
        self.v_layout_filter.addWidget(self.lbl_filter_size)
        self.sl_filter_size = QtWidgets.QSlider(self.tab_filters)
        self.sl_filter_size.setOrientation(QtCore.Qt.Horizontal)
        self.sl_filter_size.setObjectName("sl_filter_size")
        self.v_layout_filter.addWidget(self.sl_filter_size)
        self.lbl_filter_params = QtWidgets.QLabel(self.tab_filters)
        self.lbl_filter_params.setObjectName("lbl_filter_params")
        self.v_layout_filter.addWidget(self.lbl_filter_params)
        self.edit_filter_params = QtWidgets.QLineEdit(self.tab_filters)
        self.edit_filter_params.setObjectName("edit_filter_params")
        self.v_layout_filter.addWidget(self.edit_filter_params)
        self.btn_insert_filter = QtWidgets.QPushButton(self.tab_filters)
        self.btn_insert_filter.setObjectName("btn_insert_filter")
        self.v_layout_filter.addWidget(self.btn_insert_filter)
        self.horizontalLayout_3.addLayout(self.v_layout_filter)
        self.tabs_options.addTab(self.tab_filters, "")
        self.tab_segmentations = QtWidgets.QWidget()
        self.tab_segmentations.setObjectName("tab_segmentations")
        self.tabs_options.addTab(self.tab_segmentations, "")
        self.v_layou_options.addWidget(self.tabs_options)
        self.h_layout_options = QtWidgets.QHBoxLayout()
        self.h_layout_options.setObjectName("h_layout_options")
        self.btn_equalize = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_equalize.sizePolicy().hasHeightForWidth())
        self.btn_equalize.setSizePolicy(sizePolicy)
        self.btn_equalize.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_equalize.setFlat(False)
        self.btn_equalize.setObjectName("btn_equalize")
        self.h_layout_options.addWidget(self.btn_equalize)
        self.radio_compare = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_compare.sizePolicy().hasHeightForWidth())
        self.radio_compare.setSizePolicy(sizePolicy)
        self.radio_compare.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radio_compare.setAutoExclusive(False)
        self.radio_compare.setObjectName("radio_compare")
        self.h_layout_options.addWidget(self.radio_compare)
        self.radio_hist = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_hist.sizePolicy().hasHeightForWidth())
        self.radio_hist.setSizePolicy(sizePolicy)
        self.radio_hist.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.radio_hist.setChecked(True)
        self.radio_hist.setAutoExclusive(False)
        self.radio_hist.setObjectName("radio_hist")
        self.h_layout_options.addWidget(self.radio_hist)
        self.v_layou_options.addLayout(self.h_layout_options)
        self.h_layout_original_image = QtWidgets.QHBoxLayout()
        self.h_layout_original_image.setObjectName("h_layout_original_image")
        self.replace_original_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_original_image.sizePolicy().hasHeightForWidth())
        self.replace_original_image.setSizePolicy(sizePolicy)
        self.replace_original_image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.replace_original_image.setObjectName("replace_original_image")
        self.h_layout_original_image.addWidget(self.replace_original_image)
        self.v_layou_options.addLayout(self.h_layout_original_image)
        self.h_layout_central.addLayout(self.v_layou_options)
        self.v_layout_edited_image = QtWidgets.QVBoxLayout()
        self.v_layout_edited_image.setContentsMargins(0, -1, -1, -1)
        self.v_layout_edited_image.setObjectName("v_layout_edited_image")
        self.replace_edited_image = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replace_edited_image.sizePolicy().hasHeightForWidth())
        self.replace_edited_image.setSizePolicy(sizePolicy)
        self.replace_edited_image.setObjectName("replace_edited_image")
        self.v_layout_edited_image.addWidget(self.replace_edited_image)
        self.h_layout_central.addLayout(self.v_layout_edited_image)
        self.verticalLayout.addLayout(self.h_layout_central)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_fixed_status = QtWidgets.QLabel(self.centralwidget)
        self.lbl_fixed_status.setObjectName("lbl_fixed_status")
        self.horizontalLayout.addWidget(self.lbl_fixed_status)
        self.lbl_status_msg = QtWidgets.QLabel(self.centralwidget)
        self.lbl_status_msg.setObjectName("lbl_status_msg")
        self.horizontalLayout.addWidget(self.lbl_status_msg)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuSobre = QtWidgets.QMenu(self.menubar)
        self.menuSobre.setObjectName("menuSobre")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionSobre = QtWidgets.QAction(MainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addAction(self.actionReset)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuSobre.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs_options.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Medical Images App"))
        self.lbl_noise.setText(_translate("MainWindow", "Ruído:"))
        self.lbl_noise_amount.setText(_translate("MainWindow", "Quantidade:"))
        self.lbl_noise_params.setText(_translate("MainWindow", "Parâmetros:"))
        self.btn_insert_noise.setText(_translate("MainWindow", "Inserir"))
        self.lbl_filter.setText(_translate("MainWindow", "Filtro:"))
        self.lbl_filter_size.setText(_translate("MainWindow", "Size:"))
        self.lbl_filter_params.setText(_translate("MainWindow", "Parâmetros:"))
        self.btn_insert_filter.setText(_translate("MainWindow", "Inserir"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_filters), _translate("MainWindow", "Filtros"))
        self.tabs_options.setTabText(self.tabs_options.indexOf(self.tab_segmentations), _translate("MainWindow", "Segmentação"))
        self.btn_equalize.setText(_translate("MainWindow", "Equalizar"))
        self.radio_compare.setText(_translate("MainWindow", "Comparar"))
        self.radio_hist.setText(_translate("MainWindow", "Histograma"))
        self.replace_original_image.setText(_translate("MainWindow", "Original Image"))
        self.replace_edited_image.setText(_translate("MainWindow", "Edited Image"))
        self.lbl_fixed_status.setText(_translate("MainWindow", "Status:"))
        self.lbl_status_msg.setText(_translate("MainWindow", "Iniciado."))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuSobre.setTitle(_translate("MainWindow", "Sobre"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionSobre.setText(_translate("MainWindow", "Sobre"))

