# Generated by Django 2.1.9 on 2019-09-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleImageModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_modifier', models.CharField(choices=[('BRIGHTNESS', 'Brightness'), ('CONTRAST', 'Contrast'), ('NEGATIVE', 'Negative'), ('IDENTITY', 'Identity'), ('LOGARITHMIC', 'Logarithmic'), ('EXPONENTIAL', 'Exponential'), ('POWER', 'Power')], max_length=11, verbose_name='Type of Modifier *')),
                ('argument_name', models.CharField(max_length=255)),
                ('argument_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('applied_date', models.DateTimeField(auto_now=True)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im2webapp.ImageModel')),
            ],
        ),
    ]
