# Generated by Django 2.2.6 on 2019-10-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0002_simpleimagemodifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleImageModifier',
            new_name='ItensityImageModifier',
        ),
    ]
