# Generated by Django 2.2.6 on 2019-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0003_auto_20191024_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
