# Generated by Django 2.2.6 on 2019-10-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0004_imagemodel_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseImageModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noise_type', models.CharField(choices=[('uniform', 'Uniform'), ('gaussian', 'Gaussian'), ('rayleight', 'Rayleight'), ('exponential', 'Exponential'), ('gamma', 'Gamma'), ('salt_and_pepper', 'Salt and Pepper')], max_length=15, verbose_name='Type of Noise *')),
                ('argument1_name', models.CharField(max_length=255)),
                ('argument1_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('argument2_name', models.CharField(max_length=255)),
                ('argument2_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('applied_date', models.DateTimeField(auto_now=True)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im2webapp.ImageModel')),
            ],
        ),
    ]
