# Generated by Django 2.2.6 on 2019-10-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0005_noiseimagemodifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noiseimagemodifier',
            name='amount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount: '),
        ),
        migrations.AlterField(
            model_name='noiseimagemodifier',
            name='argument2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='noiseimagemodifier',
            name='argument2_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='noiseimagemodifier',
            name='noise_type',
            field=models.CharField(choices=[('uniform', 'Uniform'), ('gaussian', 'Gaussian'), ('rayleight', 'Rayleight'), ('exponential', 'Exponential'), ('gamma', 'Gamma'), ('salt_and_pepper', 'Salt and Pepper')], max_length=15, verbose_name='Noise Type: '),
        ),
    ]
