# Generated by Django 2.2.6 on 2019-11-06 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0006_auto_20191027_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterImageModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(choices=[('gaussian', 'Gaussian'), ('uniform', 'Uniform'), ('median', 'Median'), ('maximum', 'Maximum'), ('minimum', 'Minimum'), ('sharpening', 'Sharpening'), ('percentile', 'Percentile'), ('wiener', 'Wiener'), ('sobel', 'Sobel')], max_length=10, verbose_name='Noise Type: ')),
                ('argument1_name', models.CharField(max_length=255)),
                ('argument1_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('size_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount: ')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('applied_date', models.DateTimeField(auto_now=True)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='im2webapp.ImageModel')),
            ],
        ),
    ]
