# Generated by Django 2.2.6 on 2019-11-06 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0007_filterimagemodifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensityImageModifier',
            new_name='IntensityImageModifier',
        ),
    ]
