# Generated by Django 2.2.6 on 2019-11-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0008_auto_20191106_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='intensityimagemodifier',
            name='saved_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='noiseimagemodifier',
            name='saved_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
