# Generated by Django 2.2.6 on 2019-11-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0009_auto_20191112_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterimagemodifier',
            name='saved_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
