# Generated by Django 2.2.6 on 2019-11-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0010_filterimagemodifier_saved_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterimagemodifier',
            name='filter_type',
            field=models.CharField(choices=[('gaussian', 'Gaussian'), ('uniform', 'Uniform'), ('median', 'Median'), ('maximum', 'Maximum'), ('minimum', 'Minimum'), ('sharpening', 'Sharpening'), ('percentile', 'Percentile'), ('wiener', 'Wiener'), ('sobel', 'Sobel')], max_length=10, verbose_name='Filter Type: '),
        ),
        migrations.AlterField(
            model_name='filterimagemodifier',
            name='size_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Size: '),
        ),
    ]
