# Generated by Django 2.2.6 on 2020-05-04 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('im2webapp', '0012_auto_20191113_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='imagemodel',
            unique_together={('user', 'slug')},
        ),
    ]
