# Generated by Django 2.2.6 on 2020-11-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('im2webapp', '0013_auto_20200504_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('images_zip_file', models.FileField(upload_to='images_zip/', verbose_name='Images File Zip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='image_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='im2webapp.ImageGroupModel'),
        ),
    ]
