# Generated by Django 2.2.6 on 2020-11-17 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0014_auto_20201117_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegroupmodel',
            name='images_zip_file',
            field=models.FileField(upload_to='images_zip/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip'])], verbose_name='Images File Zip'),
        ),
    ]
