# Generated by Django 2.2.6 on 2020-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('im2webapp', '0016_auto_20201117_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='is_covid',
            field=models.BooleanField(default=False, verbose_name='COVID'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='processada',
            field=models.BooleanField(default=False, verbose_name='Processada'),
        ),
    ]
