# Generated by Django 2.1.7 on 2019-06-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_user_profile_with_picture_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../static/images/profile-default.jpg', upload_to='profile_pics'),
        ),
    ]
